version: '3.6'
services:
    vosint-event-hpc07:
        image: vienai/vosint-backendevent:1.0.2
        ports: 
            - 9107:6101             
        environment:
            - ENVIRONMENT=PRODUCTION
            - MONGO_DETAILS=mongodb://admin:aivosint%400258@mong7.vosint.edu.vn:60007/admin?authSource=admin&authMechanism=SCRAM-SHA-256
            - mong_host=mongodb://admin:aivosint%400258@mong7.vosint.edu.vn:60007/admin?authSource=admin&authMechanism=SCRAM-SHA-256
            - DATABASE_NAME=vosint_db
            - PIPELINE_API=http://vosint-pipeline-master:6101
            - KAFKA_CONNECT=kafka-1:9092,kafka-2:9092
            - ELASTIC_CONNECT=http://master5:9200,http://master6:9200
            - EXTRACT_API=http://vosint-eventextraction-hpc07:1510/extract
            - SUMMARIZE_API=http://vosint-sumthesis-hpc07:1510/ext

        deploy:
            restart_policy:
                condition: on-failure
            replicas: 1      
            placement:
                constraints:
                    - node.hostname==hpc07  
        networks:
            - vosint3_system_network

networks: 
  vosint3_system_network:
    external: true

